INSERT INTO tb_category (id, name, description) VALUES(null, 'Eletrônico', 'Produtos eletrônicos em geral.')
INSERT INTO tb_category (id, name, description) VALUES(null, 'Móveis', 'Móveis eletrônicos em geral.')
INSERT INTO tb_category (id, name, description) VALUES(null, 'Cozinha', 'Utensílios de cozinha.')
INSERT INTO tb_category (id, name, description) VALUES(null, 'Vestuário', 'Roupas masculinas e femininas.')

INSERT INTO tb_product(id, name, description, price, active, tag, category_id) VALUES(null, 'Celular LG K9', 'Celular LG K9 última geração', 699.66, true, 'celular lg',1)
INSERT INTO tb_product(id, name, description, price, active, tag, category_id) VALUES(null, 'Notebook Dell', 'Notebook Dell i7 8GB Ram', 1592.67, false, 'Notebook dell', 1)
INSERT INTO tb_product(id, name, description, price, active, tag, category_id) VALUES(null, 'Armário 6 portas', 'Armário 6 portas 4 gavetas', 456.66, true, 'armário guarda-roupa', 2)
INSERT INTO tb_product(id, name, description, price, active, tag, category_id) VALUES(null, 'Panela de pressão', 'Panela de pressão 6L', 125.89, true, 'panela pressão', 3)
INSERT INTO tb_product(id, name, description, price, active, tag, category_id) VALUES(null, 'Camiseta Masculina', 'Camiseta Masculina Nike', 125.66, true, 'camisa camiseta', 4)
INSERT INTO tb_product(id, name, description, price, active, tag, category_id) VALUES(null, 'Camiseta Feminina', 'Camiseta Masculina Adidas', 699.66, true, 'camisa camiseta', 4)
